all: 
# gcc -I headers sdl2_lib/include/SDL.h sdl2_lib/include/SDL_ttf.h lib/*.c gbemu/main.c -L . -l SDL2 SDL2_ttf -o part
# gcc -I headers sdl2_lib/include/SDL.h sdl2_lib/include/SDL_ttf.h pthread-win32/pthread.h lib/*.c gbemu/main.c -L . -lSDL2 -lSDL2_ttf -o part
# gcc -I headers sdl2_lib/include/SDL.h sdl2_lib/include/SDL_ttf.h lib/*.c gbemu/main.c -L . -lSDL2 -lSDL2_ttf -o part
	gcc -I headers sdl2_lib/include/SDL.h sdl2_lib/include/SDL_ttf.h pthread-win32/pthread.h lib/*.c gbemu/main.c -L . -lSDL2 -lSDL2_ttf -o part